anchor_to_edges = true
icon_theme = "Paper"
position = "bottom"

#[[end]]
#music_dir = "/home/jake/Music"
#player_type = "mpd"
#type = "music"

#[end.truncate]
#max_length = 100
#mode = "end"
#[[end]]
#cmd = "/home/jake/bin/phone-battery"
#type = "script"

#[end.show_if]
#cmd = "/home/jake/bin/phone-connected"
#interval = 500

[[end]]
format = [
    "    CPU {cpu_percent}% | {temp_c:coretemp-Package-id-0}°C",
    "RAM {memory_used} / {memory_total} GB ({memory_percent}%)",
    "DRV {disk_percent:/}% {disk_percent:/home}%",
    "⇅ {net_down:eno2} / {net_up:eno2} Mbps",
    "AVG {load_average:1} | {load_average:5} | {load_average:15}",
    "UP {uptime}",
]
type = "sys_info"

[end.interval]
cpu = 1
disks = 300
memory = 30
networks = 3
temps = 5

[[end]]
max_items = 3
type = "clipboard"

[[end]]
type = "tray"

#[end.truncate]
#length = 50
#mode = "end"

[[end.popup]]
orientation = "vertical"
type = "box"

[[end.popup.widgets]]
label = "Power menu"
name = "header"
type = "label"

[[end.popup.widgets]]
type = "box"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!shutdown now"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!reboot"
type = "button"

[[end.popup.widgets]]
label = "Uptime: {{30000:uptime -p | cut -d ' ' -f2-}}"
name = "uptime"
type = "label"

[[end]]
type = "clock"

[[start]]
all_monitors = false
type = "workspaces"

[[start]]
label = "    asx @ asx-hypr    "
type = "label"

[[start]]
player_type = "mpris"
type = "music"
icons.play = "󰓇 "

